### ISSUE TITLE
wrong numbered list on github.io

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACE1docs.jl#2]
The github view properly numbers the items on (https://github.com/ACEsuit/ACE1docs.jl/blob/main/docs/src/gettingstarted/installation.md#), but the [github.io view](https://acesuit.github.io/ACE1docs.jl/dev/gettingstarted/installation/) shows 1., 2., 1., 1. ....

**Comment by bernstei** [comment]
I think the code block has to be indented to not interrupt the numbering, but don't have write permission to be able to make a PR to test this (also, is it possible to view the github.io version when it's a PR, before it's merged?).

**Comment by cortner** [comment]
Thank you, Noam. I'll look at your issues as I find the time. But I've also given you push access. Don't worry about PRs, just push directly to `main` while we are still writing the majority of the docs; I trust people to be sensible. 

Personally, I tend to edit on GitHub; just switch to the docs src and then press "." - this will open a VS code inside the browser, you can edit, then directly commit to the `main` branch. I find this very convenient, but it is a matter of taste of course.

**Comment by wcwitt** [comment]
I removed the numbers when I broke it into subsections

**Comment by cortner** [comment]
closed by #4
