### ISSUE TITLE
beginner docs one liner and long version not consistent

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACE1docs.jl#3]
The one liner at the beginning of the installation instructions does not have the "activate ." step that's in the long version.

**Comment by bernstei** [comment]
Also, the one liner still refers to `ACE` rather than `ACE1`.

**Comment by cortner** [comment]
I'm wondering now whether to remove the one-liner altogether.

**Comment by cortner** [comment]
Or at least we should clarify what this does and doesn't do.

**Comment by cortner** [comment]
Closed by #4
