### ISSUE TITLE
Best practices for adding specific versions of packages

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACE1docs.jl#5]
What are the differences between `add Package@1.2.3` and setting `[compat] Package = "1.2.3"` in `Project.toml`? It seems like the `add` version is insufficient by itself because things can break on package update. But is it redundant to do both?

We should figure this out and adjust the installation docs accordingly.

**Comment by bernstei** [comment]
The `add ..@version` just installs that version.  I'm pretty sure that if you set compat before the add, it'll add the latest version that's compatible.  If you add, then set compat, you have to do `] up` to downgrade to a compatible version.

**Comment by wcwitt** [comment]
Oh okay I hadn't experimented with any of that - thanks

**Comment by cortner** [comment]
Closed by #4
